### ISSUE TITLE
Requiring a name field for the layer configuration

### ISSUE THREAD

**Issue by waggonerjake** [manwaring/serverless-prune-versions#12]
When trying to use this to prune layers, it may be worth mentioning that having the `name` field is required in the layer configuration for this to work even though its optional on AWS' end, as shown here: https://www.serverless.com/framework/docs/providers/aws/guide/layers#configuration

In the serverless.yaml, these 2 things are required for the layer configuration for this plugin to work:
```
layers:
  myLayer:
    path: /path/to/layer
    name: myLayer <-- This MUST be populated for this plugin to work
```
If the layer does not have the `name` field, then this plugin will fail and you'll get an error like `Missing required key 'LayerName' in params`. It would probably be best to mention this in the README or something for future reference so users know they need to include the _optional_ name parameter for this plugin to work.

Here is my current custom plugin config, if youre curious:
```
custom:
  prune:
    automatic: true
    includeLayers: true
    number: 3
    layer: myLayer
```
